[theme]
mode = "dark"

[bar.default]
position = "top"


[wallpaper]
enabled = true
fill_mode = "stretch"
directory = "/home/brennen/nixos-dots/walls/"

[wallpaper.default]
path = "/home/brennen/nixos-dots/walls/walls3.jpg"
