keys:
  - &brennen age1993z4aptqa7fhgvw86uhupp9usr6jeshaxv89y6samdwud2yhe4samgh37

creation_rules:
  - path_regex: secrets/brennen.yaml$
    key_groups:
      - age:
        - *brennen

#  - path_regex: secrets/services/[^/]+\.(yaml|json|env|ini)$
#    key_groups:
#      - age:
#        - *brennen

